import React from 'react';
import { motion } from "framer-motion";
import { useNavigate } from 'react-router-dom';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import {
  AlertTriangle,
  DollarSign,
  TrendingDown,
  Lightbulb,
  Download,
  ArrowLeft,
  Crown,
  CheckCircle,
  ExternalLink
} from 'lucide-react';
import DashboardLayout from '../components/layout/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Progress } from '../components/ui/progress';
import { useData } from '../context/DataContext';
import { toast } from 'sonner';

const SEVERITY_COLORS = {
  high: 'hsl(0, 72%, 58%)',
  medium: 'hsl(38, 92%, 50%)',
  low: 'hsl(145, 60%, 40%)'
};

export default function FinancialLeaks() {
  const { feeAnalysis, linkedBanks, subscription, FEE_RULES } = useData();
  const navigate = useNavigate();
  const isPremium = subscription.plan === 'premium';

  if (!isPremium) {
    return (
      <DashboardLayout title="Financial Leaks" subtitle="Detailed breakdown of your banking fees">
        <Card className="max-w-lg mx-auto">
          <CardContent className="py-12 text-center">
            <Crown className="h-16 w-16 mx-auto mb-4 text-accent" />
            <h2 className="text-2xl font-bold mb-2">Premium Feature</h2>
            <p className="text-muted-foreground mb-6">
              Financial leaks is available for Premium subscribers. Upgrade to unlock detailed fee breakdowns and savings recommendations.
            </p>
            <Button onClick={() => navigate('/pricing')} className="gap-2">
              <Crown className="h-4 w-4" />
              Upgrade to Premium - $9.99/mo
            </Button>
          </CardContent>
        </Card>
      </DashboardLayout>
    );
  }

  if (!feeAnalysis || linkedBanks.length === 0) {
    return (
      <DashboardLayout title="Financial Leaks" subtitle="Detailed breakdown of your banking fees">
        <Card className="max-w-lg mx-auto">
          <CardContent className="py-12 text-center">
            <AlertTriangle className="h-16 w-16 mx-auto mb-4 text-muted-foreground/30" />
            <h2 className="text-2xl font-bold mb-2">No Bank Linked</h2>
            <p className="text-muted-foreground mb-6">
              Link your bank account to analyze your transactions and detect fee mismatches.
            </p>
            <Button onClick={() => navigate('/bank-linking')}>
              Link Bank Account
            </Button>
          </CardContent>
        </Card>
      </DashboardLayout>
    );
  }

  // Prepare chart data
  const pieData = feeAnalysis.feesByType.map(fee => ({
    name: fee.name,
    value: fee.total,
    fill: SEVERITY_COLORS[fee.severity]
  }));

  const barData = feeAnalysis.feesByType.map(fee => ({
    name: fee.name.split(' ')[0],
    amount: fee.total,
    count: fee.count,
    fill: fee.avoidable ? SEVERITY_COLORS.medium : SEVERITY_COLORS.low
  }));

  const handleDownloadPDF = () => {
    // Generate text report
    const reportText = `
OLI-BRANCH Financial Leaks REPORT
==============================
Generated: ${new Date().toLocaleDateString()}

SUMMARY
-------
Total Fees Found: $${feeAnalysis.totalFees.toFixed(2)}
Avoidable Fees: $${feeAnalysis.avoidableFees.toFixed(2)}
Potential Monthly Savings: $${feeAnalysis.savingsPotential.toFixed(2)}
Fee Mismatch Score: ${feeAnalysis.mismatchScore}/100

FEE BREAKDOWN
-------------
${feeAnalysis.feesByType.map(fee => `
${fee.name}
  Total: $${fee.total.toFixed(2)} (${fee.count} occurrences)
  Severity: ${fee.severity.toUpperCase()}
  Avoidable: ${fee.avoidable ? 'Yes' : 'No'}
  Recommendation: ${fee.recommendation}
`).join('')}

RECOMMENDATIONS
---------------
${feeAnalysis.feesByType.filter(f => f.avoidable).map((fee, i) => `${i + 1}. ${fee.recommendation}`).join('\n')}

---
Report generated by Oli-Branch Financial Dashboard
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `oli-branch-financial-leaks-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  return (
    <DashboardLayout title="Financial Leaks" subtitle="Detailed breakdown of your banking fees">
      <div className="space-y-6">
        {/* Back Button */}
        <Button variant="ghost" onClick={() => navigate('/bank-linking')} className="gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back to Bank Linking
        </Button>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Fees</p>
                    <p className="text-3xl font-bold text-destructive">${feeAnalysis.totalFees.toFixed(2)}</p>
                  </div>
                  <div className="p-3 rounded-full bg-destructive/10">
                    <DollarSign className="h-6 w-6 text-destructive" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Avoidable Fees</p>
                    <p className="text-3xl font-bold text-warning">${feeAnalysis.avoidableFees.toFixed(2)}</p>
                  </div>
                  <div className="p-3 rounded-full bg-warning/10">
                    <AlertTriangle className="h-6 w-6 text-warning" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Potential Savings</p>
                    <p className="text-3xl font-bold text-success">${feeAnalysis.savingsPotential.toFixed(2)}</p>
                  </div>
                  <div className="p-3 rounded-full bg-success/10">
                    <TrendingDown className="h-6 w-6 text-success" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Mismatch Score</p>
                    <p className="text-3xl font-bold text-foreground">{feeAnalysis.mismatchScore}/100</p>
                  </div>
                  <div className="p-3 rounded-full bg-primary/10">
                    <AlertTriangle className="h-6 w-6 text-primary" />
                  </div>
                </div>
                <Progress value={feeAnalysis.mismatchScore} className="mt-3 h-2" />
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Fee Distribution Pie */}
          <Card>
            <CardHeader>
              <CardTitle>Fee Distribution</CardTitle>
              <CardDescription>Breakdown by fee type</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={4}
                      dataKey="value"
                      strokeWidth={0}
                    >
                      {pieData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(value) => `$${value.toFixed(2)}`} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="flex flex-wrap justify-center gap-4 mt-4">
                {pieData.map((entry) => (
                  <div key={entry.name} className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full" style={{ backgroundColor: entry.fill }} />
                    <span className="text-sm text-muted-foreground">{entry.name}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Fee Amounts Bar Chart */}
          <Card>
            <CardHeader>
              <CardTitle>Fee Amounts by Type</CardTitle>
              <CardDescription>Total amount per category</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={barData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" tick={{ fontSize: 11 }} />
                    <YAxis stroke="hsl(var(--muted-foreground))" />
                    <Tooltip formatter={(value) => `$${value.toFixed(2)}`} />
                    <Bar dataKey="amount" radius={[8, 8, 0, 0]}>
                      {barData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Fee Details */}
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Fee Breakdown & Recommendations</CardTitle>
              <CardDescription>Detailed analysis with actionable recommendations</CardDescription>
            </div>
            <Button onClick={handleDownloadPDF} className="gap-2">
              <Download className="h-4 w-4" />
              Download PDF Report
            </Button>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {feeAnalysis.feesByType.map((fee, index) => (
                <motion.div
                  key={fee.type}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className={`p-4 rounded-lg border ${
                    fee.severity === 'high' ? 'bg-destructive/5 border-destructive/30' :
                    fee.severity === 'medium' ? 'bg-warning/5 border-warning/30' :
                    'bg-muted/50 border-border'
                  }`}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <AlertTriangle className={`h-5 w-5 ${
                        fee.severity === 'high' ? 'text-destructive' :
                        fee.severity === 'medium' ? 'text-warning' : 'text-muted-foreground'
                      }`} />
                      <div>
                        <h4 className="font-semibold">{fee.name}</h4>
                        <p className="text-sm text-muted-foreground">{fee.description}</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold">${fee.total.toFixed(2)}</p>
                      <p className="text-sm text-muted-foreground">{fee.count} occurrences</p>
                    </div>
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Badge variant={fee.severity === 'high' ? 'destructive' : fee.severity === 'medium' ? 'warning' : 'secondary'}>
                        {fee.severity} priority
                      </Badge>
                      {fee.avoidable && (
                        <Badge variant="outline" className="text-success border-success">
                          <CheckCircle className="h-3 w-3 mr-1" />
                          Avoidable
                        </Badge>
                      )}
                    </div>
                  </div>
                  
                  <div className="mt-3 p-3 rounded-lg bg-card border border-border">
                    <div className="flex items-start gap-2">
                      <Lightbulb className="h-4 w-4 text-accent shrink-0 mt-0.5" />
                      <p className="text-sm">{fee.recommendation}</p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
